[package]
name = "imap-client"
description = "Rust library to manage IMAP clients"
version = "0.1.5"
authors = ["soywod <clement.douin@posteo.net>"]
edition = "2021"
license = "MIT"
categories = ["email"]
keywords = ["email", "imap", "client"]
homepage = "https://pimalaya.org/"
documentation = "https://github.com/pimalaya/imap-client/"
repository = "https://github.com/pimalaya/imap-client/"

[dev-dependencies]
static_assertions = "1.1"
tokio = { version = "1.37", features = ["full"] }

[dependencies]
imap-next = { version = "0.3", features = ["expose_stream", "tag_generator", "starttls", "ext_id", "ext_metadata"] }
rustls-platform-verifier = "0.3"
thiserror = "1"
tokio = { version = "1.37", features = ["net", "time"] }
tokio-rustls = { version = "0.26", default-features = false, features = ["logging", "ring", "tls12"] }
tracing = "0.1"
