[package]
name = "imap-client"
description = "Rust library to manage IMAP clients"
version = "0.1.4"
authors = ["soywod <clement.douin@posteo.net>"]
edition = "2021"
license = "MIT"
categories = ["email"]
keywords = ["email", "imap", "client"]
homepage = "https://pimalaya.org/"
documentation = "https://github.com/pimalaya/imap-client/"
repository = "https://github.com/pimalaya/imap-client/"

[dev-dependencies]
static_assertions = "1.1"
tokio = { version = "1.37", features = ["full"] }

[dependencies]
imap-next = { version = "0.2", features = ["expose_stream", "tag_generator", "starttls", "ext_id", "ext_metadata"] }
once_cell = "1"
rustls-native-certs = "0.8"
thiserror = "1"
tokio = { version = "1.37", features = ["net", "time"] }
tokio-rustls = { version = "0.26", default-features = false, features = ["logging", "tls12", "ring"] }
tracing = "0.1"

[patch.crates-io]
imap-next = { git = "https://github.com/duesee/imap-next" }
